<?php
/**
 * Created by PhpStorm.
 * User: artycake
 * Date: 8/15/16
 * Time: 15:46
 */
require_once 'vendor/autoload.php';
$hyena = new \Jeroenherczeg\Hyena\Hyena();
$domains = [
    ['domain' => 'http://10days.nl', 'good' => true],
    ['domain' => 'http://123kamerplanten.com', 'good' => true],
    ['domain' => 'http://3suisses.be', 'good' => true],
    ['domain' => 'http://4ff.be', 'good' => true],
    ['domain' => 'http://aaiaai.be', 'good' => true],
    ['domain' => 'http://aaiko.com', 'good' => true],
    ['domain' => 'http://aapnootmies.be', 'good' => true],
    ['domain' => 'http://abercrombie.com', 'good' => true],
    ['domain' => 'http://abercrombiefitch.com', 'good' => true],
    ['domain' => 'http://aceandtate.nl', 'good' => true],
    ['domain' => 'http://achterdemaan.com', 'good' => true],
    ['domain' => 'http://addmyberry.com', 'good' => true],
    ['domain' => 'http://addmyberry.comafdmyberry.com', 'good' => true], // FAIL
    ['domain' => 'http://adhemar.be', 'good' => true],
//    ['domain' => 'http://adidas.be', 'good' => true], // FAIL
    ['domain' => 'http://aecraft.tictail.com', 'good' => true],
    ['domain' => 'http://afdmyberry.com', 'good' => true], // FAIL
    ['domain' => 'http://ainz.nl', 'good' => true],
    ['domain' => 'http://albelli.be', 'good' => true],
    ['domain' => 'http://albelli.nl', 'good' => true],
    ['domain' => 'http://alexandalexa.com', 'good' => true],
    ['domain' => 'http://alfamale.be', 'good' => true],
    ['domain' => 'http://aliexpress.com', 'good' => true],
    ['domain' => 'http://alittlelovelycompany.nl', 'good' => true],
    ['domain' => 'http://alittlemorelikethis.com', 'good' => true],
    ['domain' => 'http://all-essentials.com', 'good' => true],
    ['domain' => 'http://allsaints.com', 'good' => true],
    ['domain' => 'http://amazon.co.uk', 'good' => true], // FAIL
    ['domain' => 'http://amazon.de', 'good' => true],
    ['domain' => 'http://ambertree.be', 'good' => true],
    ['domain' => 'http://america-today.com', 'good' => true],
    ['domain' => 'http://amicamea.be', 'good' => true], // FAIL
    ['domain' => 'http://amletero.be', 'good' => true],
    ['domain' => 'http://amorie.be', 'good' => true],
    ['domain' => 'http://amormoda.nl', 'good' => true],
    ['domain' => 'http://anatevsic.com', 'good' => true],
    ['domain' => 'http://angino.com', 'good' => true],
    ['domain' => 'http://angular.be', 'good' => true],
    ['domain' => 'http://animauxspeciaux.be', 'good' => true],
    ['domain' => 'http://aninebing.com', 'good' => true],
    ['domain' => 'http://anna-nina.nl', 'good' => true],
    ['domain' => 'http://annapops.be', 'good' => true],
    ['domain' => 'http://anne-sophie.be', 'good' => true],
    ['domain' => 'http://annekejanneke.be', 'good' => true],
    ['domain' => 'http://anneliestimmermans.com', 'good' => true],
    ['domain' => 'http://anthropologie.eu', 'good' => true],
    ['domain' => 'http://antjesfashion.nl', 'good' => true],
    ['domain' => 'http://antwerpavenue.com', 'good' => true],
    ['domain' => 'http://ao1976.com', 'good' => true],
    ['domain' => 'http://apenkopje.nl', 'good' => true],
    ['domain' => 'http://aprilvisje.be', 'good' => true],
    ['domain' => 'http://ara.com', 'good' => null],
    ['domain' => 'http://areyousmooth.be', 'good' => true],
    ['domain' => 'http://armistice-store.fr', 'good' => true],
    ['domain' => 'http://arper.com', 'good' => true],
    ['domain' => 'http://arte.be', 'good' => true], // FAIL
    ['domain' => 'http://artifactuprising.com', 'good' => true],
    ['domain' => 'http://artsymodern.com', 'good' => true], // FAIL
    ['domain' => 'http://asadventure.com', 'good' => true],
    ['domain' => 'http://asiisa.nl', 'good' => true],
    ['domain' => 'http://asos.com', 'good' => true],
    ['domain' => 'http://aspasia.be', 'good' => true],
    ['domain' => 'http://atelierpapier.be', 'good' => true],
    ['domain' => 'http://atelierpyknic.com', 'good' => true], // FAIL
    ['domain' => 'http://atticempire.com', 'good' => true], // FAIL
    ['domain' => 'http://attitudeholland.nl', 'good' => true],
    ['domain' => 'http://aubadestore.be', 'good' => true],
    ['domain' => 'https://ba-sh.com', 'good' => false], // X
    ['domain' => 'http://babazou.be', 'good' => true],
    ['domain' => 'http://babsilou.be', 'good' => true],
    ['domain' => 'http://baby-label.com', 'good' => true],
    ['domain' => 'http://babysprouts.com', 'good' => true],
    ['domain' => 'http://babyswishlist.be', 'good' => true],
    ['domain' => 'http://babyvalue.be', 'good' => true],
    ['domain' => 'http://bagatelles-lingerie.com', 'good' => true], //FAIL
    ['domain' => 'http://bambiblauw.be', 'good' => true],
    ['domain' => 'http://basicapparel.dk', 'good' => true],
    ['domain' => 'http://bazarnumerotrois.com', 'good' => true],
    ['domain' => 'http://be-bymagalipinchasi.com', 'good' => true],
    ['domain' => 'http://be-glam-belgium.myshopify.com', 'good' => true],
    ['domain' => 'http://be.avanceshoes.com', 'good' => true],
    ['domain' => 'http://be.nextdirect.com', 'good' => true],
    ['domain' => 'http://be.tommy.com', 'good' => true],
    ['domain' => 'http://beadsbyromys.nl', 'good' => true],
    ['domain' => 'http://beaublue.be', 'good' => true],
    ['domain' => 'http://beaumonde-fashion.be', 'good' => true],
    ['domain' => 'http://beautiful-bijoux.com', 'good' => true],
    ['domain' => 'http://beauty88.nl', 'good' => true],
    ['domain' => 'http://beautybay.com', 'good' => true],
    ['domain' => 'http://beautymelon.be', 'good' => true],
    ['domain' => 'http://bebe-au-naturel.com', 'good' => true],
    ['domain' => 'http://bebe-saisons.fr', 'good' => true],
    ['domain' => 'http://becksondergaard.com', 'good' => true],
    ['domain' => 'http://beenature.be', 'good' => true],
    ['domain' => 'http://beeyou.be', 'good' => true],
    ['domain' => 'http://beforetheyrefamous.be', 'good' => true],
    ['domain' => 'http://beglam.be', 'good' => true], // FAIL
    ['domain' => 'http://bel-bo.be', 'good' => false],
    ['domain' => 'http://belgianpickles.com', 'good' => true],
    ['domain' => 'http://bella-boutique.nl', 'good' => true],
    ['domain' => 'http://bellasinella.be', 'good' => true],
    ['domain' => 'http://bellelien.be', 'good' => true],
    ['domain' => 'http://bellerose.be', 'good' => true],
    ['domain' => 'http://bengeltjeskidsstore.be', 'good' => true],
    ['domain' => 'http://bent.be', 'good' => true],
    ['domain' => 'http://bercadeau.be', 'good' => true],
    ['domain' => 'http://bershka.com', 'good' => null],
    ['domain' => 'http://beshoes.be', 'good' => true],
    ['domain' => 'http://bestseller.com', 'good' => true], // FAIL
    ['domain' => 'http://bijenkorf.nl', 'good' => true],
    ['domain' => 'http://bijoupolis.be', 'good' => true],
    ['domain' => 'http://bijzondermooi.nl', 'good' => true],
    ['domain' => 'http://bikinisonline.eu', 'good' => true],
    ['domain' => 'http://billyrose.be', 'good' => true],
    ['domain' => 'http://bimbi.be', 'good' => true], // FAIL
    ['domain' => 'http://birchbox.fr', 'good' => true],
    ['domain' => 'http://bitchplease.be', 'good' => true],
    ['domain' => 'http://biteswelove.be', 'good' => null],
    ['domain' => 'http://bizjoe.be', 'good' => true],
    ['domain' => 'http://blabloem.be', 'good' => true],
    ['domain' => 'http://blabloom.be', 'good' => true],
    ['domain' => 'http://blabloom.com', 'good' => true],
    ['domain' => 'http://blacklily.dk', 'good' => true],
    ['domain' => 'http://blissconcept.be', 'good' => false], // X
    ['domain' => 'http://blokker.be', 'good' => true],
    ['domain' => 'http://blokxiishop.nl', 'good' => true],
    ['domain' => 'http://bloomon.be', 'good' => true],
    ['domain' => 'http://bluebelle.nl', 'good' => true],
    ['domain' => 'http://bluepointstore.be', 'good' => true],
    ['domain' => 'http://blushboutique.be', 'good' => true], // FAIL
    ['domain' => 'http://bmini.eu', 'good' => true],
    ['domain' => 'http://bobilly.be', 'good' => true],
    ['domain' => 'http://bobotremelo.be', 'good' => true],
    ['domain' => 'http://bodesigns.be', 'good' => true],
    ['domain' => 'http://bodesigns.com', 'good' => true],
    ['domain' => 'http://bodyandbess.com', 'good' => true],
    ['domain' => 'http://boeckie.myshopify.com', 'good' => true],
    ['domain' => 'http://boekhandelpardoes.be', 'good' => true],
    ['domain' => 'http://boerenenburen.be', 'good' => true],
    ['domain' => 'http://boetiekruth.be', 'good' => true],
    ['domain' => 'http://bohobabes.eu', 'good' => true],
    ['domain' => 'http://bol.com', 'good' => null],
    ['domain' => 'http://bolddesign.be', 'good' => true],
    ['domain' => 'http://bollebuik-be.be', 'good' => true],
    ['domain' => 'http://bollebuik.be', 'good' => true],
    ['domain' => 'http://bolletjeseend.be', 'good' => true],
    ['domain' => 'http://boohoo.com', 'good' => true],
    ['domain' => 'http://bookdepository.com', 'good' => true],
    ['domain' => 'http://booking.com', 'good' => true],
    ['domain' => 'http://booksinbelgium.be', 'good' => false], // X
    ['domain' => 'http://boomf.com', 'good' => true],
    ['domain' => 'http://boozyshop.nl', 'good' => true],
    ['domain' => 'http://bormans-modeschoenen.nl', 'good' => null],
    ['domain' => 'http://bottines.nl', 'good' => true],
    ['domain' => 'http://boxworx.nl', 'good' => true],
    ['domain' => 'http://boyslabel.com', 'good' => true],
    ['domain' => 'http://brandymelville.de', 'good' => true],
    ['domain' => 'http://brandymelvilleusa.com', 'good' => null],
    ['domain' => 'http://brantano.be', 'good' => true],
    ['domain' => 'http://breadandboxers.com', 'good' => true],
    ['domain' => 'http://brindilles.fr', 'good' => true],
    ['domain' => 'http://brokebikes.eu', 'good' => true], // FAIL
    ['domain' => 'http://brooklyn.be', 'good' => true],
    ['domain' => 'http://buddyandbear.com', 'good' => true],
    ['domain' => 'http://buissonniere.com', 'good' => true],
    ['domain' => 'http://buitendelijntjes.nl', 'good' => true],
    ['domain' => 'http://buitendelijntjesshop.com', 'good' => true],
    ['domain' => 'http://buymeonce.com', 'good' => true],
    ['domain' => 'http://bykloe.com', 'good' => true],
    ['domain' => 'http://bylenz.be', 'good' => true],
    ['domain' => 'http://bymalenebirger.com', 'good' => true],
    ['domain' => 'http://bymeaccessories.nl', 'good' => true], // FAIL
    ['domain' => 'http://bymusthaves.com', 'good' => true],
    ['domain' => 'http://byrebellion.nl', 'good' => null], // ?
    ['domain' => 'http://bysiri.nl', 'good' => true],
    ['domain' => 'http://byvar.com', 'good' => true],
    ['domain' => 'http://c-and-a.com', 'good' => false], // X
    ['domain' => 'http://callaliladameskleding.be', 'good' => true],
    ['domain' => 'http://camaieu.com', 'good' => true],
    ['domain' => 'http://camomile.london', 'good' => true],
    ['domain' => 'http://capricci.nl', 'good' => true],
    ['domain' => 'http://caramel-shop.co.uk', 'good' => true],
    ['domain' => 'http://carlijnq.nl', 'good' => true],
    ['domain' => 'http://casennina.be', 'good' => true],
    ['domain' => 'http://cassis.be', 'good' => true],
    ['domain' => 'http://cathalogue.be', 'good' => true],
    ['domain' => 'http://celebrityfashion.be', 'good' => true],
    ['domain' => 'http://centrecommercial.cc', 'good' => true],
    ['domain' => 'http://cereal.be', 'good' => true],
    ['domain' => 'http://chalo.eu', 'good' => true],
    ['domain' => 'http://charliemag.be', 'good' => true],
    ['domain' => 'http://charliemary.com', 'good' => true],
    ['domain' => 'http://charlinescloset.be', 'good' => true],
    ['domain' => 'http://chatmechant.be', 'good' => true],
    ['domain' => 'http://chaussea.com', 'good' => true],
    ['domain' => 'http://cheapasszonnebrillen.nl', 'good' => null],
    ['domain' => 'http://cherrylisious.be', 'good' => true],
    ['domain' => 'http://childrensalon.com', 'good' => true],
    ['domain' => 'http://choosme.be', 'good' => true],
    ['domain' => 'http://chouchous.fr', 'good' => true],
    ['domain' => 'http://cime-skincare.com', 'good' => true],
    ['domain' => 'http://cirkeltje.be', 'good' => true],
    ['domain' => 'http://cks-fashion.com', 'good' => true],
    ['domain' => 'http://clodette.be', 'good' => true],
    ['domain' => 'http://close-up.be', 'good' => true],
    ['domain' => 'http://closeup.be', 'good' => true],
    ['domain' => 'http://clouds9000.com', 'good' => null],
    ['domain' => 'http://cloudsoffashion.be', 'good' => true],
    ['domain' => 'http://cloudsoffashion.com', 'good' => true],
    ['domain' => 'http://clusewatches.com', 'good' => true],
    ['domain' => 'http://cocodrilo.be', 'good' => false], // X
    ['domain' => 'http://coeur-maison.be', 'good' => true],
    ['domain' => 'http://colourfulrebel.com', 'good' => true], // X
    ['domain' => 'http://comegetfashion.com', 'good' => true],
    ['domain' => 'http://commelesloups.com', 'good' => true],
    ['domain' => 'http://comptoirdescotonniers.com', 'good' => true],
    ['domain' => 'http://comptoirdesobjets.com', 'good' => true],
    ['domain' => 'http://confetti-kinderkleding.be', 'good' => true],
    ['domain' => 'http://coolblue.be', 'good' => true],
    ['domain' => 'http://coolcat.be', 'good' => true],
    ['domain' => 'http://copineshasselt.be', 'good' => true],
    ['domain' => 'http://corakemperman.nl', 'good' => true],
    ['domain' => 'http://cosisaidso.com', 'good' => true],
    ['domain' => 'http://cosmeticary.com', 'good' => true],
    ['domain' => 'http://cosstores.com', 'good' => true],
    ['domain' => 'http://cothe.be', 'good' => true],
    ['domain' => 'http://cottonandscents.com', 'good' => true],
    ['domain' => 'http://couleurlocale.eu', 'good' => true],
    ['domain' => 'http://courage-fashion.be', 'good' => true],
    ['domain' => 'http://coureurdumonde.com', 'good' => true],
    ['domain' => 'http://cozykidz.nl', 'good' => true],
    ['domain' => 'http://creatingcollective.com', 'good' => true],
    ['domain' => 'http://crowdyhouse.com', 'good' => true],
    ['domain' => 'http://daily-poetry.nl', 'good' => true],
    ['domain' => 'http://damoyantwerp.com', 'good' => true],
    ['domain' => 'http://daniellevroemen.com', 'good' => true],
    ['domain' => 'http://daphnyraes.com', 'good' => true],
    ['domain' => 'http://dappershoe.nl', 'good' => true],
    ['domain' => 'http://dasmag.nl', 'good' => true],
    ['domain' => 'http://de blauwe kapitein.be', 'good' => true], // FAIL
    ['domain' => 'http://de fabriceur.nl', 'good' => true], // FAIL
    ['domain' => 'http://debestekamer.be', 'good' => true],
    ['domain' => 'http://debijenkorf.nl', 'good' => true],
    ['domain' => 'http://deblauwekapitein.be', 'good' => true],
    ['domain' => 'http://decathlon.be', 'good' => true],
    ['domain' => 'http://decovry.be', 'good' => true],
    ['domain' => 'http://decovry.com', 'good' => true],
    ['domain' => 'http://deens.nl', 'good' => true],
    ['domain' => 'http://deensekroon.nl', 'good' => true],
    ['domain' => 'http://def-shop.nl', 'good' => true],
    ['domain' => 'http://defermetisten.be', 'good' => true],
    ['domain' => 'http://degeleflamingo.be', 'good' => true],
    ['domain' => 'http://degeleflamingo.com', 'good' => true],
    ['domain' => 'http://degoudenlegende.be', 'good' => true], // FAIL
    ['domain' => 'http://degroenekapoen.be', 'good' => true],
    ['domain' => 'http://dehoutwagen.nl', 'good' => true],
    ['domain' => 'http://dekleineballon.be', 'good' => true], // FAIL
    ['domain' => 'http://dekleineuil.be', 'good' => true],
    ['domain' => 'http://deleukedingen.nl', 'good' => true],
    ['domain' => 'http://deleye.be', 'good' => true],
    ['domain' => 'http://delika.eu', 'good' => true],
    ['domain' => 'http://delphinequirin.be', 'good' => true],
    ['domain' => 'http://den-depot.be', 'good' => true],
    ['domain' => 'http://denkzuid.be', 'good' => true],
    ['domain' => 'http://deoorbel.be', 'good' => true],
    ['domain' => 'http://deparis.me', 'good' => true],
    ['domain' => 'http://deptstoreforthemind.com', 'good' => true],
    ['domain' => 'http://designersremix.com', 'good' => true],
    ['domain' => 'http://designiswolf.be', 'good' => true],
    ['domain' => 'http://designletters.dk', 'good' => null], // ?
    ['domain' => 'http://designoriginals.online', 'good' => true], // FAIL
    ['domain' => 'http://despetitshauts.com', 'good' => true],
    ['domain' => 'http://destoffenkamer.be', 'good' => true],
    ['domain' => 'http://destoffenknop.be', 'good' => true],
    ['domain' => 'http://destoffenmadam.be', 'good' => true],
    ['domain' => 'http://destoffenstraat.com', 'good' => true],
    ['domain' => 'http://detafelvanamandine.be', 'good' => true], // FAIL
    ['domain' => 'http://dexters.be', 'good' => true],
    ['domain' => 'http://di.be', 'good' => true],
    ['domain' => 'http://diapers-and-milk.com', 'good' => true],
    ['domain' => 'http://dille-kamille.be', 'good' => true],
    ['domain' => 'http://dilleenkamille.be', 'good' => true], // FAIL
    ['domain' => 'http://diloco.be', 'good' => true],
    ['domain' => 'http://dimancheabamako.be', 'good' => true],
    ['domain' => 'http://disneycouture.co.uk', 'good' => true],
    ['domain' => 'http://displate.com', 'good' => true],
    ['domain' => 'http://ditverzinjeniet.be', 'good' => true],
    ['domain' => 'http://donebydeer.com', 'good' => true],
    ['domain' => 'http://doozo.be', 'good' => true], // FAIL
    ['domain' => 'http://dorothyperkins.com', 'good' => true],
    ['domain' => 'http://dotcomgiftshop.com', 'good' => true],
    ['domain' => 'http://douglas.nl', 'good' => true], // FAIL
    ['domain' => 'http://douglasandbec.com', 'good' => true],
    ['domain' => 'http://drankgigant.nl', 'good' => true],
    ['domain' => 'http://dreamkey.nl', 'good' => true],
    ['domain' => 'http://dreamland.be', 'good' => true],
    ['domain' => 'http://dressedupshop.nl', 'good' => true],
    ['domain' => 'http://dressesonly.be', 'good' => true],
    ['domain' => 'http://dressesonly.nl', 'good' => true],
    ['domain' => 'http://driedeco.be', 'good' => true],
    ['domain' => 'http://drinkecos.com', 'good' => true],
    ['domain' => 'http://drinklets.nl', 'good' => true],
    ['domain' => 'http://druantia.be', 'good' => true],
    ['domain' => 'http://ducksday.com', 'good' => true],
    ['domain' => 'http://due.be', 'good' => true],
    ['domain' => 'http://dutchglories.com', 'good' => true], // FAIL
    ['domain' => 'http://dwhjewelry.nl', 'good' => true],
    ['domain' => 'http://e5mode.be', 'good' => true],
    ['domain' => 'http://earnieland.be', 'good' => true],
    ['domain' => 'http://easy-clothes.com', 'good' => true],
    ['domain' => 'http://ebay.co.uk', 'good' => true],
    ['domain' => 'http://eclecticeccentricity.bigcartel.com', 'good' => true],
    ['domain' => 'http://eco-logisch.be', 'good' => true],
    ['domain' => 'http://ecoshop.be', 'good' => true],
    ['domain' => 'http://edisac.be', 'good' => true],
    ['domain' => 'http://editionsdoa.tictail.com', 'good' => true],
    ['domain' => 'http://egg-baby.com', 'good' => true],
    ['domain' => 'http://elisestore.nl', 'good' => true],
    ['domain' => 'http://elleetmoi.net', 'good' => true],
    ['domain' => 'http://ellemila.be', 'good' => true], // FAIL
    ['domain' => 'http://ellemillashop.com', 'good' => true],
    ['domain' => 'http://emetmoi.be', 'good' => true],
    ['domain' => 'http://emilea.be', 'good' => true],
    ['domain' => 'http://emob.be', 'good' => true],
    ['domain' => 'http://emonkibiza.com', 'good' => true],
    ['domain' => 'http://en.emoi-emoi.com', 'good' => true],
    ['domain' => 'http://enes.be', 'good' => true],
    ['domain' => 'http://enlasnubes.nl', 'good' => true],
    ['domain' => 'http://ensuus.nl', 'good' => true],
    ['domain' => 'http://ernstings-family.de', 'good' => true],
    ['domain' => 'http://espoo.be', 'good' => true],
    ['domain' => 'http://esprit.be', 'good' => true],
    ['domain' => 'http://esprit.com', 'good' => true],
    ['domain' => 'http://essentiel-antwerp.com', 'good' => true],
    ['domain' => 'http://essentiel-antwerpen.com', 'good' => true], // FAIL
    ['domain' => 'http://etam.com', 'good' => true],
    ['domain' => 'http://etsy.com', 'good' => true],
    ['domain' => 'http://eu.abercrombie.com', 'good' => true],
    ['domain' => 'http://eu.artifactuprising.com', 'good' => true],
    ['domain' => 'http://eu.christianlouboutin.com', 'good' => true],
    ['domain' => 'http://eu.hollisterco.com', 'good' => true],
    ['domain' => 'http://eu.riverisland.com', 'good' => true],
    ['domain' => 'http://eu.topshop.com', 'good' => true],
    ['domain' => 'http://euro.dorothyperkins.com', 'good' => true],
    ['domain' => 'http://eva-store.pswebshop.com', 'good' => true], // FAIL
    ['domain' => 'http://eyeslipsface.be', 'good' => null], // ?
    ['domain' => 'http://ezisliving.com', 'good' => null], // ?
    ['domain' => 'http://fabelab.dk', 'good' => true],
    ['domain' => 'http://fablebaby.com.au', 'good' => true],
    ['domain' => 'http://fabrikk.be', 'good' => true],
    ['domain' => 'http://fabriquemagique.be', 'good' => true],
    ['domain' => 'http://fairplace.be', 'good' => true],
    ['domain' => 'http://fantasylove.nl', 'good' => true],
    ['domain' => 'http://farfetch.com', 'good' => true],
    ['domain' => 'http://farmaline.be', 'good' => false], // X
    ['domain' => 'http://fashh.nl', 'good' => true],
    ['domain' => 'http://fashion-click.nl', 'good' => true],
    ['domain' => 'http://fashion-stories.be', 'good' => true],
    ['domain' => 'http://fashionbydemi.nl', 'good' => true],
    ['domain' => 'http://fashionchick.be', 'good' => true],
    ['domain' => 'http://fashiondesignproducts.nl', 'good' => true],
    ['domain' => 'http://fenandned.com', 'good' => true], // FAIL
    ['domain' => 'http://fermetisten.be', 'good' => true], // FAIL
    ['domain' => 'http://fermliving.com', 'good' => true],
    ['domain' => 'http://fest.amsterdam', 'good' => true],
    ['domain' => 'http://fifi-lapin.blogspot.be', 'good' => true],
    ['domain' => 'http://filippa-k.com', 'good' => true],
    ['domain' => 'http://fillesapapa.com', 'good' => true],
    ['domain' => 'http://filoufriends.com', 'good' => true],
    ['domain' => 'http://finelittleday.com', 'good' => true],
    ['domain' => 'http://finnconcepts.com', 'good' => true],
    ['domain' => 'http://fleurfatale.be', 'good' => true],
    ['domain' => 'http://fleux.com', 'good' => true],
    ['domain' => 'http://fleux.fr', 'good' => true], // FAIL
    ['domain' => 'http://flinders.be', 'good' => true],
    ['domain' => 'http://flipcrown.com', 'good' => null], // ?
    ['domain' => 'http://floom.be', 'good' => true],
    ['domain' => 'http://florenceandtheboys.be', 'good' => true],
    ['domain' => 'http://fluokoffie.be', 'good' => true],
    ['domain' => 'http://flying-tiger.be', 'good' => true],
    ['domain' => 'http://folkster.com', 'good' => true],
    ['domain' => 'http://fonq.be', 'good' => true],
    ['domain' => 'http://foodbag.', 'good' => true], // FAIL
    ['domain' => 'http://foodbag.be', 'good' => true],
    ['domain' => 'http://foodbandits.nl', 'good' => true],
    ['domain' => 'http://foodwelove.nl', 'good' => true],
    ['domain' => 'http://forever21.com', 'good' => true],
    ['domain' => 'http://fotocover.be', 'good' => true],
    ['domain' => 'http://fotogoed.nl', 'good' => null], // ?
    ['domain' => 'http://fr.sandro-paris.com', 'good' => true],
    ['domain' => 'http://freddypantroom.be', 'good' => true],
    ['domain' => 'http://fredenginger.com', 'good' => true], // FAIL
    ['domain' => 'http://fredginger.com', 'good' => true],
    ['domain' => 'http://froydind.com', 'good' => true],
    ['domain' => 'http://funkycherry.be', 'good' => true],
    ['domain' => 'http://funni.be', 'good' => true],
    ['domain' => 'http://furnified.com', 'good' => true],
    ['domain' => 'http://gallerys.be', 'good' => true],
    ['domain' => 'http://gandhara.be', 'good' => true],
    ['domain' => 'http://gap.com', 'good' => true],
    ['domain' => 'http://gap.eu', 'good' => true],
    ['domain' => 'http://gardnerandthegang.com', 'good' => true],
    ['domain' => 'http://gaspard-by-cl.be', 'good' => true],
    ['domain' => 'http://georgette.be', 'good' => true],
    ['domain' => 'http://gestuz.com', 'good' => true],
    ['domain' => 'http://gewoonjip.nl', 'good' => true], // FAIL
    ['domain' => 'http://gewoonstijl.nl', 'good' => true],
    ['domain' => 'http://giksmode.be', 'good' => true],
    ['domain' => 'http://gingercollections.be', 'good' => true],
    ['domain' => 'http://gingerwald.com', 'good' => true],
    ['domain' => 'http://gintonicshop.be', 'good' => true],
    ['domain' => 'http://girlslabel.com', 'good' => true],
    ['domain' => 'http://givenfashion.com', 'good' => true],
    ['domain' => 'http://glampings.nl', 'good' => true],
    ['domain' => 'http://godsavequeens.com', 'good' => true],
    ['domain' => 'http://goedgemerkt.nl', 'good' => true],
    ['domain' => 'http://goedvantoen.nl', 'good' => true],
    ['domain' => 'http://goeiezin.com', 'good' => true],
    ['domain' => 'http://goldfish.be', 'good' => true],
    ['domain' => 'http://goodies-shop.nl', 'good' => true],
    ['domain' => 'http://google.be', 'good' => true],
    ['domain' => 'http://google.com', 'good' => true],
    ['domain' => 'http://graceandmila.com', 'good' => true],
    ['domain' => 'http://grampa-paris.com', 'good' => true],
    ['domain' => 'http://grand-illusions.com', 'good' => true], // FAIL
    ['domain' => 'http://grandst.com', 'good' => true],
    ['domain' => 'http://grasonderjevoeten.nl', 'good' => true],
    ['domain' => 'http://greenjump.nl', 'good' => null], // ?
    ['domain' => 'http://guess.eu', 'good' => true],
    ['domain' => 'http://gutsgusto.com', 'good' => true],
    ['domain' => 'http://gutsgusto.nl', 'good' => true],
    ['domain' => 'http://h&m.be', 'good' => true], // FAIL
    ['domain' => 'http://h&m.com', 'good' => true], // FAIL
    ['domain' => 'http://haarshop.nl', 'good' => true],
    ['domain' => 'http://hajp.be', 'good' => true],
    ['domain' => 'http://handwritten.nl', 'good' => true],
    ['domain' => 'http://happeak.lt', 'good' => true],
    ['domain' => 'http://happybluebox.be', 'good' => true],
    ['domain' => 'http://happyhippo.be', 'good' => true],
    ['domain' => 'http://happyleonie.tictail.com', 'good' => true],
    ['domain' => 'http://hardgraft.com', 'good' => true],
    ['domain' => 'http://hausmerk.com', 'good' => true],
    ['domain' => 'http://hbcare.nl', 'good' => true],
    ['domain' => 'http://helenb.be', 'good' => true],
    ['domain' => 'http://hellofresh.be', 'good' => true],
    ['domain' => 'http://hellomydear.be', 'good' => true],
    ['domain' => 'http://hema.be', 'good' => true],
    ['domain' => 'http://hema.nl', 'good' => true],
    ['domain' => 'http://hemeltjelief.net', 'good' => true], //?
    ['domain' => 'http://henm.be', 'good' => true],
    ['domain' => 'http://henrietteh.com', 'good' => true],
    ['domain' => 'http://henriettes.com', 'good' => true], // FAIL
    ['domain' => 'http://hetglazenschoentje.be', 'good' => true],
    ['domain' => 'http://hetlandvanooit.be', 'good' => true],
    ['domain' => 'http://hetstoffenhuis.be', 'good' => true],
    ['domain' => 'http://hetzoetemagazijntje.be', 'good' => false], // X
    ['domain' => 'http://hiddentreasures.be', 'good' => true],
    ['domain' => 'http://hipandgreen.be', 'good' => true], // FAIL
    ['domain' => 'http://hipandgreen.com', 'good' => true],
    ['domain' => 'http://hiplikeme.nl', 'good' => true], // FAIL
    ['domain' => 'http://hippeschoentjes.be', 'good' => true],
    ['domain' => 'http://hippebaby.com', 'good' => true],
    ['domain' => 'http://hippebeebjes.nl', 'good' => true],
    ['domain' => 'http://hippeschoentjes.be', 'good' => true],
    ['domain' => 'http://hippieibiza.nl', 'good' => true],
    ['domain' => 'http://hippieshop.be', 'good' => null], // ?
    ['domain' => 'http://hispanitas.com', 'good' => true],
    ['domain' => 'http://histoiredesophie.be', 'good' => true],
    ['domain' => 'http://hm.com', 'good' => true],
    ['domain' => 'http://hoentjencreatie.nl', 'good' => true],
    ['domain' => 'http://hollekebolleke.be', 'good' => true],
    ['domain' => 'http://hollister.com', 'good' => true],
    ['domain' => 'http://hollisterco.com', 'good' => true],
    ['domain' => 'http://hossintropia.com', 'good' => true],
    ['domain' => 'http://hotstof.be', 'good' => true],
    ['domain' => 'http://house4fashion.nl', 'good' => false], // X
    ['domain' => 'http://housemates.nl', 'good' => true],
    ['domain' => 'http://houseofhackney.com', 'good' => true],
    ['domain' => 'http://houseofjamie.com', 'good' => true],
    ['domain' => 'http://houtjevanpapier.be', 'good' => true],
    ['domain' => 'http://hps.be', 'good' => true],
    ['domain' => 'http://hugo-loves-tiki.myshopify.com', 'good' => true],
    ['domain' => 'http://hugoboss.com', 'good' => false], // X
    ['domain' => 'http://huisvanmarcel.be', 'good' => true], // FAIL
    ['domain' => 'http://huisvanmarcel.com', 'good' => true], //?
    ['domain' => 'http://hunkemoller.be', 'good' => true],
    ['domain' => 'http://hunkemoller.nl', 'good' => true],
    ['domain' => 'http://huttelihut.dk', 'good' => true],
    ['domain' => 'http://huxbaby.com', 'good' => true],
    ['domain' => 'http://iamkid.be', 'good' => true],
    ['domain' => 'http://iamkid.com', 'good' => false], // X
    ['domain' => 'http://ibes-scarves.com', 'good' => true],
    ['domain' => 'http://ibizamusthaves.nl', 'good' => true],
    ['domain' => 'http://ichi.biz', 'good' => true],
    ['domain' => 'http://iciparisxl.be', 'good' => true],
    ['domain' => 'http://ikea.be', 'good' => true],
    ['domain' => 'http://ikea.com', 'good' => true],
    ['domain' => 'http://ikhebeenbril.nl', 'good' => true],
    ['domain' => 'http://ikks.com', 'good' => true],
    ['domain' => 'http://ila-shop.co', 'good' => true],
    ['domain' => 'http://ilmiocollection.com', 'good' => true],
    ['domain' => 'http://ilovespeelgoed.nl', 'good' => true],
    ['domain' => 'http://ilovevintage.com', 'good' => true],
    ['domain' => 'http://imaginjewels.be', 'good' => true],
    ['domain' => 'http://imaginjewels.com', 'good' => true],
    ['domain' => 'http://inedehaes.com', 'good' => true],
    ['domain' => 'http://inge-fran.nl', 'good' => true],
    ['domain' => 'http://iniminihomemade.be', 'good' => true],
    ['domain' => 'http://interieurliefde.nl', 'good' => null], // ?
    ['domain' => 'http://inthestyle.com', 'good' => true],
    ['domain' => 'http://iroparis.com', 'good' => null], // ?
    ['domain' => 'http://irregularchoice.com', 'good' => true],
    ['domain' => 'http://istoires.com', 'good' => true],
    ['domain' => 'http://itmustbeperfect.nl', 'good' => true],
    ['domain' => 'http://itsapresent.nl', 'good' => true],
    ['domain' => 'http://itskaos.com', 'good' => true],
    ['domain' => 'http://ivyrevel.com', 'good' => true],
    ['domain' => 'http://iwantthatmusthave.nl', 'good' => true],
    ['domain' => 'http://ixxidesign.com', 'good' => true],
    ['domain' => 'http://j-a-m.be', 'good' => true],
    ['domain' => 'http://jackyluxury.com', 'good' => true],
    ['domain' => 'http://jackz.be', 'good' => true],
    ['domain' => 'http://jadorejewelry.net', 'good' => true],
    ['domain' => 'http://jaeaccessories.be', 'good' => true],
    ['domain' => 'http://janeandjoe.be', 'good' => null], // ?
    ['domain' => 'http://jaswig.com', 'good' => true],
    ['domain' => 'http://jbc.be', 'good' => true],
    ['domain' => 'http://jeansstation.be', 'good' => true],
    ['domain' => 'http://jefavowebshop.be', 'good' => true], // FAIL
    ['domain' => 'http://jennyfer.com', 'good' => null], // ?
    ['domain' => 'http://jetaimejewels.nl', 'good' => null], // ?
    ['domain' => 'http://jeujouethique.com', 'good' => true],
    ['domain' => 'http://jewels4you.be', 'good' => true],
    ['domain' => 'http://jippiejajee.nl', 'good' => true],
    ['domain' => 'http://joloves.com', 'good' => true],
    ['domain' => 'http://jogha.com', 'good' => true],
    ['domain' => 'http://joker.be', 'good' => true],
    ['domain' => 'http://jollychic.com', 'good' => true],
    ['domain' => 'http://joloves.com', 'good' => true],
    ['domain' => 'http://jooltje.nl', 'good' => true],
    ['domain' => 'http://jordangrace.com', 'good' => true],
    ['domain' => 'http://josenjuul.be', 'good' => true], // FAIL
    ['domain' => 'http://joyoflittlethings.com', 'good' => true],
    ['domain' => 'http://jules-co.be', 'good' => true],
    ['domain' => 'http://julijasshop.be', 'good' => true],
    ['domain' => 'http://julyadrichem.com', 'good' => true],
    ['domain' => 'http://jumelle.be', 'good' => true], // FAIL
    ['domain' => 'http://juneandjulian.com', 'good' => true],
    ['domain' => 'http://juneandjullian.com', 'good' => true], // FAIL
    ['domain' => 'http://juriannematter.nl', 'good' => true],
    ['domain' => 'http://justfemale.com', 'good' => null], // ?
    ['domain' => 'http://justjulia.be', 'good' => true],
    ['domain' => 'http://jutenjuul.nl', 'good' => null], // ?
    ['domain' => 'http://jutkaenriska.nl', 'good' => true],
    ['domain' => 'http://juttu.be', 'good' => true],
    ['domain' => 'http://kaatenco.be', 'good' => true],
    ['domain' => 'http://kadoinhuis.nl', 'good' => true],
    ['domain' => 'http://kamera-express.nl', 'good' => true],
    ['domain' => 'http://kameraexpress.be', 'good' => true],
    ['domain' => 'http://kastenco.be', 'good' => null], // ?
    ['domain' => 'http://katrienvanhecke.com', 'good' => true],
    ['domain' => 'http://keecie.nl', 'good' => true],
    ['domain' => 'http://keeosk.com', 'good' => true],
    ['domain' => 'http://kewlox.be', 'good' => true],
    ['domain' => 'http://kiabi.be', 'good' => true],
    ['domain' => 'http://kickpack-shop.de', 'good' => true],
    ['domain' => 'http://kiddiffit.com', 'good' => true],
    ['domain' => 'http://kidooz.nl', 'good' => true],
    ['domain' => 'http://kidsdepartment.nl', 'good' => true],
    ['domain' => 'http://kidsdinge.be', 'good' => true],
    ['domain' => 'http://kidslovesneakers.nl', 'good' => true],
    ['domain' => 'http://kidswithflair.com', 'good' => true],
    ['domain' => 'http://kidwild.com', 'good' => true],
    ['domain' => 'http://kimsalabling.nl', 'good' => true],
    ['domain' => 'http://kinderenkoning.be', 'good' => true],
    ['domain' => 'http://kindschoen.be', 'good' => true], // FAIL
    ['domain' => 'http://kindzoblij.nl', 'good' => true],
    ['domain' => 'http://kinglouie.nl', 'good' => true],
    ['domain' => 'http://kiwifabrics.be', 'good' => true],
    ['domain' => 'http://kixx-online.nl', 'good' => null], // ?
    ['domain' => 'http://kleineheld.be', 'good' => true],
    ['domain' => 'http://kleinekoning.nl', 'good' => true],
    ['domain' => 'http://kleinenoorman.be', 'good' => true],
    ['domain' => 'http://kleinenstoer.nl', 'good' => null], // ?
    ['domain' => 'http://kleineviking.be', 'good' => true],
    ['domain' => 'http://kleinezebra.be', 'good' => true],
    ['domain' => 'http://kleinezebra.com', 'good' => true],
    ['domain' => 'http://klijntje.be', 'good' => true],
    ['domain' => 'http://knijter.nl', 'good' => true],
    ['domain' => 'http://knipengoshop.be', 'good' => true],
    ['domain' => 'http://knotandbow.com', 'good' => true],
    ['domain' => 'http://kokkie.be', 'good' => true],
    ['domain' => 'http://komono.com', 'good' => true],
    ['domain' => 'http://konoandorca.com', 'good' => true],
    ['domain' => 'http://koppiewebs.be', 'good' => true],
    ['domain' => 'http://kousenenkarton.be', 'good' => null], // ?
    ['domain' => 'http://krijtwit.be', 'good' => true], // FAIL
    ['domain' => 'http://krijtwit.nl', 'good' => true],
    ['domain' => 'http://kruidvat.be', 'good' => true],
    ['domain' => 'http://kudzu.be', 'good' => true],
    ['domain' => 'http://kwiziner.be', 'good' => true],
    ['domain' => 'http://labee.com', 'good' => true],
    ['domain' => 'http://labelcrush.com', 'good' => true],
    ['domain' => 'http://labellov.com', 'good' => true],
    ['domain' => 'http://labottega.be', 'good' => true],
    ['domain' => 'http://labottegardiane.com', 'good' => true],
    ['domain' => 'http://lacemarket.us', 'good' => true],
    ['domain' => 'http://ladyjane.be', 'good' => true],
    ['domain' => 'http://lafabrika.be', 'good' => true],
    ['domain' => 'http://lafavo.be', 'good' => true],
    ['domain' => 'http://lamuzette.be', 'good' => true],
    ['domain' => 'http://lanassieraden.nl', 'good' => true],
    ['domain' => 'http://laredoute.be', 'good' => true],
    ['domain' => 'http://large.be', 'good' => true],
    ['domain' => 'http://laurencedevallez.be', 'good' => true], // FAIL
    ['domain' => 'http://laurencedevallez.com', 'good' => true], // FAIL
    ['domain' => 'http://leboutique.n', 'good' => true], // FAIL
    ['domain' => 'http://leboutique.nl', 'good' => true],
    ['domain' => 'http://lechaperonunlimited.com', 'good' => true],
    ['domain' => 'http://leduc-puurs.be', 'good' => true],
    ['domain' => 'http://leeandme.be', 'good' => true],
    ['domain' => 'http://lefties.com', 'good' => true],
    ['domain' => 'http://lelastof.be', 'good' => true],
    ['domain' => 'http://lelleeefashion.nl', 'good' => true],
    ['domain' => 'http://lepetitatelierdeparis.bigcartel.com', 'good' => true],
    ['domain' => 'http://les-enfants-terribles-shop.be', 'good' => true],
    ['domain' => 'http://les-folies.be', 'good' => true],
    ['domain' => 'http://lesamismaroquinerie.com', 'good' => true],
    ['domain' => 'http://lesbelges.com', 'good' => true],
    ['domain' => 'http://lescopinesdabord.net', 'good' => true],
    ['domain' => 'http://lesetalages.be', 'good' => true],
    ['domain' => 'http://lessentieldemarcelle.be', 'good' => true],
    ['domain' => 'http://lessoeurs.be', 'good' => true],
    ['domain' => 'http://letouristeperdu.com', 'good' => true],
    ['domain' => 'http://leukvoordeheb.com', 'good' => true],
    ['domain' => 'http://levi.com', 'good' => null], // ?
    ['domain' => 'http://lhistoiredeceleste.be', 'good' => true],
    ['domain' => 'http://liekeland.nl', 'good' => true],
    ['domain' => 'http://lienhereijgers.be', 'good' => true],
    ['domain' => 'http://liesellove.be', 'good' => true],
    ['domain' => 'http://lifestylespot.be', 'good' => true],
    ['domain' => 'http://lightinthebox.com', 'good' => true],
    ['domain' => 'http://lilagrace.be', 'good' => true], // FAIL
    ['domain' => 'http://lillefant.be', 'good' => true],
    ['domain' => 'http://lillefant.com', 'good' => true],
    ['domain' => 'http://lily-31.myshopify.com', 'good' => true],
    ['domain' => 'http://lilyandthelady.com', 'good' => true],
    ['domain' => 'http://lindavs.com', 'good' => true],
    ['domain' => 'http://lindex.com', 'good' => true],
    ['domain' => 'http://lineabis.be', 'good' => true],
    ['domain' => 'http://lineandjo.com', 'good' => true],
    ['domain' => 'http://lingerie-ohlala.be', 'good' => true],
    ['domain' => 'http://lingeriebestellen.be', 'good' => true],
    ['domain' => 'http://linnenenlimoen.com', 'good' => true],
//    ['domain' => 'http://lipsy.co.uk', 'good' => true],
    ['domain' => 'http://little-indians.nl', 'good' => true],
    ['domain' => 'http://little-kings-and-queens.com', 'good' => true],
    ['domain' => 'http://little-moustache.be', 'good' => true],
    ['domain' => 'http://littleboutique.be', 'good' => true],
    ['domain' => 'http://littlecolumbine.com', 'good' => true],
    ['domain' => 'http://littlefactory.com', 'good' => true],
    ['domain' => 'http://littlefashionaddict.com', 'good' => true],
    ['domain' => 'http://littlekingarthur.com', 'good' => true],
    ['domain' => 'http://littleladybugs.nl', 'good' => null], // ?
    ['domain' => 'http://littlelulubel.com', 'good' => true],
    ['domain' => 'http://littlemoustache.be', 'good' => true], // FAIL
    ['domain' => 'http://littlerebel.com', 'good' => true],
    ['domain' => 'http://littlesoho.com', 'good' => true],
    ['domain' => 'http://littlestitching.com', 'good' => true],
    ['domain' => 'http://littlethingz.be', 'good' => true],
    ['domain' => 'http://littlewannahaves.nl', 'good' => true],
    ['domain' => 'http://living-lounge.be', 'good' => true],
    ['domain' => 'http://living.nl', 'good' => true],
    ['domain' => 'http://livingdesign.be', 'good' => true],
    ['domain' => 'http://lnknits.com', 'good' => true],
    ['domain' => 'http://loavies.com', 'good' => true],
    ['domain' => 'http://lobogato.com', 'good' => true],
    ['domain' => 'http://lolalifelines.be', 'good' => true],
    ['domain' => 'http://lolaliza.be', 'good' => true],
    ['domain' => 'http://lolaliza.com', 'good' => true],
    ['domain' => 'http://lolaskids.nl', 'good' => true],
    ['domain' => 'http://lollipop-shop.be', 'good' => true], // FAIL
    ['domain' => 'http://lookhuman.com', 'good' => true],
    ['domain' => 'http://loulechien.com', 'good' => true],
    ['domain' => 'http://lovely-vintage.nl', 'good' => true],
    ['domain' => 'http://luchtplantjes.nl', 'good' => true],
    ['domain' => 'http://luckyno7.nl', 'good' => true],
    ['domain' => 'http://lululemon.com', 'good' => true],
    ['domain' => 'http://lunabloom.be', 'good' => true],
    ['domain' => 'http://lush.nl', 'good' => true],
    ['domain' => 'http://luxedy.com', 'good' => true],
    ['domain' => 'http://lyst.com', 'good' => true],
    ['domain' => 'http://m.zara.com', 'good' => true],
    ['domain' => 'http://m2.hm.com', 'good' => true],
    ['domain' => 'http://maanfabriekje.be', 'good' => true],
    ['domain' => 'http://maasmechelenvillage.com', 'good' => true],
    ['domain' => 'http://maccosmetics.be', 'good' => true],
    ['domain' => 'http://maccosmetics.com', 'good' => true],
    ['domain' => 'http://madamevolt.com', 'good' => true],
    ['domain' => 'http://madamstoltz.nl', 'good' => true],
    ['domain' => 'http://made.com', 'good' => true],
    ['domain' => 'http://madebyvest.com', 'good' => true],
    ['domain' => 'http://maisondumonde.be', 'good' => true], // FAIL
    ['domain' => 'http://maisondumonde.com', 'good' => true], // FAIL
    ['domain' => 'http://maisongodillot.com', 'good' => true],
    ['domain' => 'http://maisonscotch.be', 'good' => true],
    ['domain' => 'http://maisonsdumonde.com', 'good' => true],
    ['domain' => 'http://maje.com', 'good' => true],
    ['domain' => 'http://makehistory.bigcartel.com', 'good' => true],
    ['domain' => 'http://makroshop.be', 'good' => true],
    ['domain' => 'http://maliekeenco.be', 'good' => true],
    ['domain' => 'http://mamzel.eu', 'good' => true],
    ['domain' => 'http://mango.com', 'good' => true],
    ['domain' => 'http://manicbags.be', 'good' => true],
    ['domain' => 'http://manufactuur.be', 'good' => true], // FAIL
    ['domain' => 'http://marchsf.com', 'good' => true], // FAIL
    ['domain' => 'http://marcoz.be', 'good' => true],
    ['domain' => 'http://marliesdekkers.com', 'good' => true],
    ['domain' => 'http://marlousvandertoorn.com', 'good' => true],
    ['domain' => 'http://marmar.dk', 'good' => true],
    ['domain' => 'http://massimodutti.be', 'good' => true],
    ['domain' => 'http://massimodutti.com', 'good' => true],
    ['domain' => 'http://matchesfashion.com', 'good' => true],
    ['domain' => 'http://matsici.be', 'good' => true],
    ['domain' => 'http://mauricecoffeeknits.com', 'good' => true],
    ['domain' => 'http://mayenne-nelen.com', 'good' => true],
    ['domain' => 'http://mayke.com', 'good' => true],
    ['domain' => 'http://maysons.nl', 'good' => true],
    ['domain' => 'http://medard-webshop.be', 'good' => true],
    ['domain' => 'http://medard.be', 'good' => true], // FAIL
    ['domain' => 'http://mediaworqs.com', 'good' => true],
    ['domain' => 'http://meerdanmooi.be', 'good' => true],
    ['domain' => 'http://mencore.com', 'good' => true],
    ['domain' => 'http://menu.as', 'good' => true],
    ['domain' => 'http://merkjesvoorkids.nl', 'good' => true],
    ['domain' => 'http://mesopretty.be', 'good' => true],
    ['domain' => 'http://message.dk', 'good' => true],
    ['domain' => 'http://mettepernille.nl', 'good' => true],
    ['domain' => 'http://mevrouwaardbei.nl', 'good' => null], // ?
    ['domain' => 'http://mevrouwdeuil.nl', 'good' => true],
    ['domain' => 'http://mi-toetie.nl', 'good' => true],
    ['domain' => 'http://mia-moi.be', 'good' => true],
    ['domain' => 'http://miekedierckx.be', 'good' => true],
    ['domain' => 'http://miesamsterdam.com', 'good' => true],
    ['domain' => 'http://mikodesign.nl', 'good' => true],
    ['domain' => 'http://milanifashion.be', 'good' => true],
    ['domain' => 'http://milkbooks.com', 'good' => true],
    ['domain' => 'http://milouzzi.nl', 'good' => true],
    ['domain' => 'http://mimpi-outlet.com', 'good' => true],
    ['domain' => 'http://miniinthebox.com', 'good' => true],
    ['domain' => 'http://minimalisma.com', 'good' => true],
    ['domain' => 'http://minimaniac.be', 'good' => true],
    ['domain' => 'http://minimiks.nl', 'good' => true],
    ['domain' => 'http://minimocksshop.com', 'good' => true],
    ['domain' => 'http://minirodini.com', 'good' => true],
    ['domain' => 'http://miniyoucreation.com', 'good' => true], // FAIL
    ['domain' => 'http://miniyoucreations.com', 'good' => true], // FAIL
    ['domain' => 'http://mintencloud.nl', 'good' => true],
    ['domain' => 'http://mio-mio.be', 'good' => true],
    ['domain' => 'http://miraclescollections.be', 'good' => null], // ?
    ['domain' => 'http://miss-p.nl', 'good' => true],
    ['domain' => 'http://missbutterfly.be', 'good' => null], // ?
    ['domain' => 'http://missfabuloes.be', 'good' => true],
    ['domain' => 'http://missguided.eu', 'good' => true],
    ['domain' => 'http://misslady.nl', 'good' => true],
    ['domain' => 'http://missmadelief.be', 'good' => true],
    ['domain' => 'http://misspoppywear.be', 'good' => true],
    ['domain' => 'http://mistercocktail.nl', 'good' => true],
    ['domain' => 'http://misterdesign.be', 'good' => true],
    ['domain' => 'http://miz-mooz.be', 'good' => true],
    ['domain' => 'http://mkfashion.nl', 'good' => true],
    ['domain' => 'http://mnkbusiness.com', 'good' => true],
    ['domain' => 'http://mntnt.fr', 'good' => true],
    ['domain' => 'http://mobelfabrik.be', 'good' => true],
    ['domain' => 'http://mobile.77onlineshop.de', 'good' => null], // ?
    ['domain' => 'http://moccamoccs.nl', 'good' => true],
    ['domain' => 'http://mode-mania.nl', 'good' => true],
    ['domain' => 'http://modemakers.be', 'good' => true],
    ['domain' => 'http://modemusthaved.com', 'good' => true], // FAIL
    ['domain' => 'http://modemusthaves.com', 'good' => true],
    ['domain' => 'http://moderood.nl', 'good' => true],
    ['domain' => 'http://moesengriet.nl', 'good' => true],
    ['domain' => 'http://mokadi.be', 'good' => true],
    ['domain' => 'http://momstothemax.be', 'good' => true],
    ['domain' => 'http://mondepot.be', 'good' => true],
    ['domain' => 'http://monkeyandbutterfly.be', 'good' => true],
    ['domain' => 'http://monkeyandmole.com', 'good' => true],
    ['domain' => 'http://monki.com', 'good' => true],
    ['domain' => 'http://monoqi.com', 'good' => true],
    ['domain' => 'http://mooi-makers.nl', 'good' => true],
    ['domain' => 'http://mooiaandemuur.com', 'good' => true],
    ['domain' => 'http://mooiedozen.be', 'good' => true],
    ['domain' => 'http://moose-in-the-city.com', 'good' => true],
    ['domain' => 'http://mooved.be', 'good' => true],
    ['domain' => 'http://morethansoup.be', 'good' => true],
    ['domain' => 'http://morphebrushes.com', 'good' => true],
    ['domain' => 'http://mostwantednl.nl', 'good' => true],
    ['domain' => 'http://mr-ego.be', 'good' => true],
    ['domain' => 'http://mrfrisko.com', 'good' => true],
    ['domain' => 'http://msbling.nl', 'good' => true],
    ['domain' => 'http://msmode.be', 'good' => true],
    ['domain' => 'http://mudchick.be', 'good' => true],
    ['domain' => 'http://multiplexx.be', 'good' => true],
    ['domain' => 'http://munt-webshop.be', 'good' => true],
    ['domain' => 'http://murlifestyle.com', 'good' => true],
    ['domain' => 'http://musjes.com', 'good' => true],
    ['domain' => 'http://musthavesforreal.com', 'good' => true],
    ['domain' => 'http://my-jewellery.com', 'good' => true],
    ['domain' => 'http://my-musthaves.com', 'good' => true],
    ['domain' => 'http://mya-bay.com', 'good' => true],
    ['domain' => 'http://myexboyfriend.be', 'good' => true], // FAIL
    ['domain' => 'http://myexboyfriend.info', 'good' => true],
    ['domain' => 'http://myhair.nl', 'good' => true],
    ['domain' => 'http://myinteriormusthaves.com', 'good' => true],
    ['domain' => 'http://mylittleday.fr', 'good' => true],
    ['domain' => 'http://myspringfield.com', 'good' => true],
    ['domain' => 'http://myuniquestyle.nl', 'good' => true],
    ['domain' => 'http://na-kd.com', 'good' => true],
    ['domain' => 'http://nagelfabriek.nl', 'good' => true],
    ['domain' => 'http://naifcare.com', 'good' => true],
    ['domain' => 'http://nanushka.hu', 'good' => true],
    ['domain' => 'http://nastygal.com', 'good' => true],
    ['domain' => 'http://nathalievleeschouwer.be', 'good' => true],
    ['domain' => 'http://nathylicious.be', 'good' => true],
    ['domain' => 'http://neckladdict.com', 'good' => true],
    ['domain' => 'http://nelly.com', 'good' => true],
    ['domain' => 'http://nespresso.com', 'good' => true],
    ['domain' => 'http://net-a-porter.com', 'good' => true],
    ['domain' => 'http://netaporter.com', 'good' => true],
    ['domain' => 'http://newlook.be', 'good' => true],
    ['domain' => 'http://newlook.com', 'good' => true],
    ['domain' => 'http://newpharma.be', 'good' => true],
    ['domain' => 'http://next.be', 'good' => false], // X
    ['domain' => 'http://next.com', 'good' => false], // X
    ['domain' => 'http://nextdirect.be', 'good' => true],
    ['domain' => 'http://nike.com', 'good' => true], // FAIL
    ['domain' => 'http://nike.nl', 'good' => true], // FAIL
    ['domain' => 'http://nimzu.be', 'good' => true],
    ['domain' => 'http://nin9.nl', 'good' => true],
    ['domain' => 'http://nl.carpetoflife.com', 'good' => true],
    ['domain' => 'http://nl.dawanda.com', 'good' => true],
    ['domain' => 'http://nl.neckermann.com', 'good' => true],
    ['domain' => 'http://nl.only.com', 'good' => null], // ?
    ['domain' => 'http://nl.sarenza.be', 'good' => true],
    ['domain' => 'http://nobeautylimits.com', 'good' => true],
    ['domain' => 'http://noctu.co.uk', 'good' => true],
    ['domain' => 'http://noltenschoenen.nl', 'good' => true],
    ['domain' => 'http://nomefurniture.com', 'good' => true],
    ['domain' => 'http://nooba.nl', 'good' => true],
    ['domain' => 'http://nordicblends.nl', 'good' => true],
    ['domain' => 'http://nordicby.be', 'good' => true],
    ['domain' => 'http://nordicliving.be', 'good' => true],
    ['domain' => 'http://nordicliving.com', 'good' => true],
    ['domain' => 'http://notonthehighstreet.com', 'good' => true],
    ['domain' => 'http://nr12.be', 'good' => true],
    ['domain' => 'http://nuitdefolie.be', 'good' => true],
    ['domain' => 'http://nunucodesigncompany.com', 'good' => true],
    ['domain' => 'http://o-ren.be', 'good' => true],
    ['domain' => 'http://o-sun.net', 'good' => true],
    ['domain' => 'http://odetothings.com', 'good' => true],
    ['domain' => 'http://oeufnyc.com', 'good' => true],
    ['domain' => 'http://ohhappyfry.com', 'good' => true],
    ['domain' => 'http://ohhdeer.com', 'good' => true],
    ['domain' => 'http://ohmydress.be', 'good' => true],
    ['domain' => 'http://ohmygoodies.eu', 'good' => true],
    ['domain' => 'http://ohmygoody.nl', 'good' => true],
    ['domain' => 'http://ohsohip.nl', 'good' => true],
    ['domain' => 'http://oliveclothing.com', 'good' => true],
    ['domain' => 'http://ollekebolleke.be', 'good' => true],
    ['domain' => 'http://omoda.be', 'good' => true],
    ['domain' => 'http://onfancy.nl', 'good' => true],
    ['domain' => 'http://only.com', 'good' => true], // FAIL
    ['domain' => 'http://ophelialingerie.be', 'good' => true],
    ['domain' => 'http://orangebag.nl', 'good' => true],
    ['domain' => 'http://orangemayonaise.be', 'good' => true], // FAIL
    ['domain' => 'http://orangemayonnaise.com', 'good' => true],
    ['domain' => 'http://orangemayonnaise.nl', 'good' => true], // FAIL
    ['domain' => 'http://organic-zoo.com', 'good' => true],
    ['domain' => 'http://organictan.nl', 'good' => true], // FAIL
    ['domain' => 'http://organiczoo.co.uk', 'good' => true],
    ['domain' => 'http://othellokleding.be', 'good' => true],
    ['domain' => 'http://outfittery.be', 'good' => true],
    ['domain' => 'http://outgrow.me', 'good' => true],
    ['domain' => 'http://oysho.com', 'good' => true],
    ['domain' => 'http://pabo.be', 'good' => null], // ?
    ['domain' => 'http://pakskeshuis.be', 'good' => true],
    ['domain' => 'http://paleis.net', 'good' => true],
    ['domain' => 'http://paperfuel.nl', 'good' => null], // ?
    ['domain' => 'http://papiergoed.nl', 'good' => true],
    ['domain' => 'http://papiermier.be', 'good' => true],
    ['domain' => 'http://paplou.be', 'good' => true],
    ['domain' => 'http://pariniantwerp.com', 'good' => true],
    ['domain' => 'http://parislondres.be', 'good' => true],
    ['domain' => 'http://partydeco.nl', 'good' => true],
    ['domain' => 'http://pearlsandswines.com', 'good' => true],
    ['domain' => 'http://peekandpack.com', 'good' => true],
    ['domain' => 'http://pepantino.be', 'good' => true], // FAIL
    ['domain' => 'http://pepatino.be', 'good' => true],
    ['domain' => 'http://personligfodelsetavla.se', 'good' => true],
    ['domain' => 'http://petit-bateau.be', 'good' => true],
    ['domain' => 'http://petitecouture.be', 'good' => true],
    ['domain' => 'http://petithercule.be', 'good' => true],
    ['domain' => 'http://petitjule.com', 'good' => true],
    ['domain' => 'http://phytplants.be', 'good' => true], // FAIL
    ['domain' => 'http://phytplants.com', 'good' => true],
    ['domain' => 'http://pieddepouleshop.be', 'good' => true],
    ['domain' => 'http://piekewieke.be', 'good' => true], // FAIL
    ['domain' => 'http://pierrotfashion.be', 'good' => null], // ?
    ['domain' => 'http://pietmoodshop.be', 'good' => true],
    ['domain' => 'http://pimkie.be', 'good' => true],
    ['domain' => 'http://pimpyourkids.com', 'good' => true],
    ['domain' => 'http://pinchtoys.com', 'good' => true],
    ['domain' => 'http://pindanutjes.be', 'good' => true],
    ['domain' => 'http://pit-pit.com', 'good' => true], // FAIL
    ['domain' => 'http://pixiemarket.com', 'good' => true],
    ['domain' => 'http://plumeskincare.be', 'good' => true],
    ['domain' => 'http://plustoys.nl', 'good' => true],
    ['domain' => 'http://polarnopyret.nl', 'good' => true],
    ['domain' => 'http://polpettine.com', 'good' => true],
    ['domain' => 'http://pommedejus.nl', 'good' => true],
    ['domain' => 'http://popupshop.net', 'good' => true],
    ['domain' => 'http://poupees-russes.be', 'good' => true],
    ['domain' => 'http://presentandcorrect.com', 'good' => true],
    ['domain' => 'http://prettypolish.nl', 'good' => true],
    ['domain' => 'http://prikkeltje.nl', 'good' => true],
    ['domain' => 'http://primark.com', 'good' => true],
    ['domain' => 'http://primarkonesies.com', 'good' => true],
    ['domain' => 'http://primarkonlineshop.eu', 'good' => true],
    ['domain' => 'http://printsenposters.nl', 'good' => true],
    ['domain' => 'http://promo-code.be', 'good' => true],
    ['domain' => 'http://promod.com', 'good' => true], // FAIL
    ['domain' => 'http://promod.eu', 'good' => true],
    ['domain' => 'http://psikhouvanjou.com', 'good' => true],
    ['domain' => 'http://psikhouvanjou.nl', 'good' => true],
    ['domain' => 'http://pullandbear.com', 'good' => true],
    ['domain' => 'http://pure-axessories.com', 'good' => true],
    ['domain' => 'http://purewooddesign.be', 'good' => true],
    ['domain' => 'http://qualivino.be', 'good' => true],
    ['domain' => 'http://quitokeeto.com', 'good' => true],
    ['domain' => 'http://raafenvos.be', 'good' => true],
    ['domain' => 'http://rad.co', 'good' => true],
    ['domain' => 'http://rad.com', 'good' => true],
    ['domain' => 'http://radbag.be', 'good' => false], // X
    ['domain' => 'http://rainpharma.com', 'good' => true],
    ['domain' => 'http://raisinnoir.be', 'good' => true],
    ['domain' => 'http://rakketak.be', 'good' => true],
    ['domain' => 'http://ravedmusthaves.com', 'good' => true],
    ['domain' => 'http://readcereal.com', 'good' => true],
    ['domain' => 'http://renstore.bigcartel.com', 'good' => true],
    ['domain' => 'http://retro-lifestyle.be', 'good' => true],
    ['domain' => 'http://retrofashion.be', 'good' => true],
    ['domain' => 'http://retronaut.be', 'good' => true],
    ['domain' => 'http://rewinddesign.be', 'good' => true],
    ['domain' => 'http://riflepaperco.com', 'good' => true],
    ['domain' => 'http://ritikashoes.com', 'good' => true],
    ['domain' => 'http://riverisland.com', 'good' => true],
    ['domain' => 'http://robotshop.com', 'good' => true],
    ['domain' => 'http://rockafinn.be', 'good' => true],
    ['domain' => 'http://rosa-lee.be', 'good' => true],
    ['domain' => 'http://rosebikes.com', 'good' => true],
    ['domain' => 'http://rubia.nu', 'good' => true],
    ['domain' => 'http://ruedelor.be', 'good' => true],
    ['domain' => 'http://sacha.be', 'good' => true], // FAIL
    ['domain' => 'http://saintbasics.com', 'good' => true],
    ['domain' => 'http://sainteve.be', 'good' => true],
    ['domain' => 'http://sakestore.nl', 'good' => true],
    ['domain' => 'http://salesflare.com', 'good' => true],
    ['domain' => 'http://sammydress.com', 'good' => true],
    ['domain' => 'http://samponette.be', 'good' => true],
    ['domain' => 'http://samsoe.com', 'good' => true],
    ['domain' => 'http://sandro-paris.com', 'good' => true],
    ['domain' => 'http://sansuellefashiononlineshop.be', 'good' => true],
    ['domain' => 'http://sarenza.be', 'good' => true],
    ['domain' => 'http://sarenza.nl', 'good' => true],
    ['domain' => 'http://sasha.be', 'good' => true],
    ['domain' => 'http://sayswoo.com', 'good' => true],
    ['domain' => 'http://scarvesandstuff.be', 'good' => true],
    ['domain' => 'http://scotch-soda.com', 'good' => true],
    ['domain' => 'http://scoutlifestyle.com', 'good' => true],
    ['domain' => 'http://sebio.be', 'good' => true],
    ['domain' => 'http://sec.3suisses.be', 'good' => true], // FAIL
    ['domain' => 'http://see-u-soon.fr', 'good' => true],
    ['domain' => 'http://selected.com', 'good' => true], // FAIL
    ['domain' => 'http://self-portrait-studio.com', 'good' => true],
    ['domain' => 'http://sensunik.be', 'good' => true],
    ['domain' => 'http://sephora.fr', 'good' => true],
    ['domain' => 'http://setareh.nl', 'good' => true], // FAIL
    ['domain' => 'http://seventyone.be', 'good' => true],
    ['domain' => 'http://sewitup.be', 'good' => true], // FAIL
    ['domain' => 'http://sexy-store.nl', 'good' => true],
    ['domain' => 'http://sezane.com', 'good' => true],
    ['domain' => 'http://shabbiesamsterdam.com', 'good' => true],
    ['domain' => 'http://shak-shuka.com', 'good' => true],
    ['domain' => 'http://shana.com', 'good' => true], // FAIL
    ['domain' => 'http://sheclothes.nl', 'good' => true],
    ['domain' => 'http://shein.com', 'good' => true],
    ['domain' => 'http://sheinside.com', 'good' => true],
    ['domain' => 'http://shoediscount.be', 'good' => true],
    ['domain' => 'http://shoemixx.nl', 'good' => true],
    ['domain' => 'http://shoes-andmore.nl', 'good' => true], // FAIL
    ['domain' => 'http://shoesofprey.com', 'good' => true],
    ['domain' => 'http://shop-foglinen.com', 'good' => true],
    ['domain' => 'http://shop-plaza.be', 'good' => true],
    ['domain' => 'http://shop.chienvert.com', 'good' => true], // FAIL
    ['domain' => 'http://shop.condor.es', 'good' => true], // FAIL
    ['domain' => 'http://shop.douglasandbec.com', 'good' => true],
    ['domain' => 'http://shop.herriottgrace.com', 'good' => true],
    ['domain' => 'http://shop.hipandhealthy.com', 'good' => true],
    ['domain' => 'http://shop.holland.com', 'good' => true],
    ['domain' => 'http://shop.imakin.nl', 'good' => true],
    ['domain' => 'http://shop.lilybalou.be', 'good' => true],
    ['domain' => 'http://shop.mango.com', 'good' => true],
    ['domain' => 'http://shop.sizable.eu', 'good' => true], // FAIL
    ['domain' => 'http://shop.weekday.com', 'good' => true],
    ['domain' => 'http://shopanaise.com', 'good' => true],
    ['domain' => 'http://shopbop.com', 'good' => true], // FAIL
    ['domain' => 'http://shopjeen.com', 'good' => true],
    ['domain' => 'http://shoplily.be', 'good' => true],
    ['domain' => 'http://shopmerimeri.com', 'good' => true], // FAIL
    ['domain' => 'http://shopseventeen.nl', 'good' => true],
    ['domain' => 'http://shoptoms.nl', 'good' => true],
    ['domain' => 'http://showroomprive.be', 'good' => true],
    ['domain' => 'http://siennagoodies.com', 'good' => true],
    ['domain' => 'http://sieradenkistje.nl', 'good' => true],
    ['domain' => 'http://siesta.be', 'good' => true],
    ['domain' => 'http://silisshop.eu', 'good' => true],
    ['domain' => 'http://simplecommebonjour.b', 'good' => true], // FAIL
    ['domain' => 'http://simplecommebonjour.net', 'good' => true],
    ['domain' => 'http://sincerelyjules.com', 'good' => true],
    ['domain' => 'http://sincerelyvalentine.com', 'good' => true],
    ['domain' => 'http://sirensongwetsuits.com', 'good' => true],
    ['domain' => 'http://sissy-boy.com', 'good' => true],
    ['domain' => 'http://sissyboy.be', 'good' => true],
    ['domain' => 'http://sixhugsandrocknroll.be', 'good' => true],
    ['domain' => 'http://sjiekebiele.be', 'good' => true],
    ['domain' => 'http://sjiekedinges.be', 'good' => true],
    ['domain' => 'http://slikhaarshop.com', 'good' => true],
    ['domain' => 'http://smallable.com', 'good' => true],
    ['domain' => 'http://smallable.fr', 'good' => true],
    ['domain' => 'http://smartmat.be', 'good' => true],
    ['domain' => 'http://smartphoto.be', 'good' => true],
    ['domain' => 'http://sneakerdistrict.nl', 'good' => true],
    ['domain' => 'http://sneakerjagers.nl', 'good' => true], // FAIL
    ['domain' => 'http://snoepoet.be', 'good' => true], // FAIL
    ['domain' => 'http://snoepzoet.be', 'good' => true],
    ['domain' => 'http://snoerboer.nl', 'good' => true],
    ['domain' => 'http://snuffelbox.nl', 'good' => true],
    ['domain' => 'http://snurkbeddengoed.nl', 'good' => true],
    ['domain' => 'http://soakedinluxury.com', 'good' => true],
    ['domain' => 'http://sobaggy.be', 'good' => true],
    ['domain' => 'http://society6.com', 'good' => true],
    ['domain' => 'http://sodancewear.be', 'good' => true],
    ['domain' => 'http://soekis.com', 'good' => true],
    ['domain' => 'http://sofieschnoorwebshop.com', 'good' => true],
    ['domain' => 'http://softcactus.be', 'good' => true],
    ['domain' => 'http://solilly.nl', 'good' => true],
    ['domain' => 'http://somethingsinside.be', 'good' => true],
    ['domain' => 'http://spartoo.be', 'good' => true],
    ['domain' => 'http://speelgoedkiki.be', 'good' => true],
    ['domain' => 'http://spellonme.com', 'good' => true], // FAIL
    ['domain' => 'http://spreenow.com', 'good' => true],
    ['domain' => 'http://springstof.eu', 'good' => true],
    ['domain' => 'http://sproet-sprout.nl', 'good' => true],
    ['domain' => 'http://stackersboxes.com', 'good' => true],
    ['domain' => 'http://standaardboekhand.be', 'good' => true], // FAIL
    ['domain' => 'http://standaardboekhandel.be', 'good' => true],
    ['domain' => 'http://sternum.be', 'good' => true],
    ['domain' => 'http://stevemadden.eu', 'good' => true],
    ['domain' => 'http://stoffen.net', 'good' => true], // FAIL
    ['domain' => 'http://stoffenmie.be', 'good' => true],
    ['domain' => 'http://stofopzolder.be', 'good' => true],
    ['domain' => 'http://store.aprilandmay.com', 'good' => true],
    ['domain' => 'http://store.diesel.com', 'good' => true],
    ['domain' => 'http://store7701015.ecwid.com', 'good' => true],
    ['domain' => 'http://stories.com', 'good' => true],
    ['domain' => 'http://straatstijl.nl', 'good' => true],
    ['domain' => 'http://stradivarius.com', 'good' => true],
    ['domain' => 'http://stratier.be', 'good' => true],
    ['domain' => 'http://studioaimee.be', 'good' => true], // FAIL
    ['domain' => 'http://studioaimee.com', 'good' => true], // FAIL
    ['domain' => 'http://studioblanche.be', 'good' => true],
    ['domain' => 'http://studiobluebird.nl', 'good' => true],
    ['domain' => 'http://studiolala.be', 'good' => true],
    ['domain' => 'http://studiooink.de', 'good' => true],
    ['domain' => 'http://studiopeloeze.be', 'good' => true],
    ['domain' => 'http://studiosanne.be', 'good' => true],
    ['domain' => 'http://studiotheo.be', 'good' => true],
    ['domain' => 'http://stylight.be', 'good' => true],
    ['domain' => 'http://styliz.be', 'good' => true],
    ['domain' => 'http://subdued.com', 'good' => true],
    ['domain' => 'http://succubus.be', 'good' => true],
    ['domain' => 'http://succubus.nl', 'good' => true],
    ['domain' => 'http://suitcase.be', 'good' => true],
    ['domain' => 'http://suitsupply.com', 'good' => true],
    ['domain' => 'http://sunday-suppers.com', 'good' => false], // X
    ['domain' => 'http://superdry.be', 'good' => true],
    ['domain' => 'http://superfoodshuis.be', 'good' => true],
    ['domain' => 'http://supergoods.be', 'good' => true],
    ['domain' => 'http://supergreenme.be', 'good' => true],
    ['domain' => 'http://supertrash.com', 'good' => true],
    ['domain' => 'http://supplypaperco.com', 'good' => true], // FAIL
    ['domain' => 'http://surveyanyplace.com', 'good' => true],
    ['domain' => 'http://suussies.nl', 'good' => true],
    ['domain' => 'http://svnty.be', 'good' => true],
    ['domain' => 'http://sweet-pants.com', 'good' => true],
    ['domain' => 'http://tadaaz.be', 'good' => true],
    ['domain' => 'http://tafelvanamandine.be', 'good' => true], // FAIL
    ['domain' => 'http://taleme.be', 'good' => true],
    ['domain' => 'http://talulabelle.nl', 'good' => true],
    ['domain' => 'http://tamaris.eu', 'good' => true],
    ['domain' => 'http://tantebetsy.com', 'good' => true],
    ['domain' => 'http://tattydevine.com', 'good' => true],
    ['domain' => 'http://tea4you.nl', 'good' => true],
    ['domain' => 'http://teamconfetti.nl', 'good' => true],
    ['domain' => 'http://tedbaker.com', 'good' => true],
    ['domain' => 'http://textielstad.nl', 'good' => true], // FAIL
    ['domain' => 'http://textthebutler.be', 'good' => true],
    ['domain' => 'http://the-broken-arm.com', 'good' => true],
    ['domain' => 'http://the-green-collection.com', 'good' => true],
    ['domain' => 'http://the189.com', 'good' => true],
    ['domain' => 'http://thedesignstudiohawarden.co.uk', 'good' => true],
    ['domain' => 'http://theemeteenverhaal.be', 'good' => true],
    ['domain' => 'http://theemeteenverhaal.eu', 'good' => true],
    ['domain' => 'http://thees.be', 'good' => true],
    ['domain' => 'http://thefinestore.com', 'good' => true],
    ['domain' => 'http://theflavorshop.be', 'good' => true], // FAIL
    ['domain' => 'http://theflockshop.be', 'good' => true],
    ['domain' => 'http://theladysaysno.be', 'good' => true], // FAIL
    ['domain' => 'http://thelittlegreenbag.nl', 'good' => true],
    ['domain' => 'http://themakeupspot.be', 'good' => true],
    ['domain' => 'http://themakeupspot.nl', 'good' => true],
    ['domain' => 'http://themusthaves.nl', 'good' => true],
    ['domain' => 'http://thenextcloset.com', 'good' => true],
    ['domain' => 'http://theoutnet.com', 'good' => true],
    ['domain' => 'http://thereformation.com', 'good' => true],
    ['domain' => 'http://theshop-belgium.be', 'good' => true],
    ['domain' => 'http://theshoponline.be', 'good' => true],
    ['domain' => 'http://thevangifts.com', 'good' => true],
    ['domain' => 'http://theweedepartmentstore.co.uk', 'good' => true],
    ['domain' => 'http://thewildkidsapparel.com', 'good' => true],
    ['domain' => 'http://thinkmarie.com', 'good' => true],
    ['domain' => 'http://thomaseglialtri.com', 'good' => true],
    ['domain' => 'http://threadless.com', 'good' => true],
    ['domain' => 'http://tiffany.com', 'good' => true],
    ['domain' => 'http://tinne-mia-webshop.nl', 'good' => true],
    ['domain' => 'http://tinycottons.com', 'good' => true],
    ['domain' => 'http://tinystore.de', 'good' => true],
    ['domain' => 'http://titiandthegermankid.com', 'good' => true],
    ['domain' => 'http://todayisagoodday.be', 'good' => true],
    ['domain' => 'http://tolajo.be', 'good' => true],
    ['domain' => 'http://toldyouso.be', 'good' => true],
    ['domain' => 'http://tootz.nl', 'good' => true],
    ['domain' => 'http://topshop.com', 'good' => true],
    ['domain' => 'http://topvintage.be', 'good' => true],
    ['domain' => 'http://topvintage.nl', 'good' => true],
    ['domain' => 'http://topwijf.storelaunchers.com', 'good' => true],
    ['domain' => 'http://torfs.be', 'good' => true],
    ['domain' => 'http://torosaurus.be', 'good' => true],
    ['domain' => 'http://totalbeauty-shop.be', 'good' => true],
    ['domain' => 'http://tothemoonandbackkids.nl', 'good' => true],
    ['domain' => 'http://treasureislands.nl', 'good' => true],
    ['domain' => 'http://trendking.nl', 'good' => true],
    ['domain' => 'http://trends4sure.nl', 'good' => true],
    ['domain' => 'http://turbulent.be', 'good' => true],
    ['domain' => 'http://turnpaard.be', 'good' => true],
    ['domain' => 'http://tutuchic.be', 'good' => true],
    ['domain' => 'http://tweemeisjes.be', 'good' => true], // FAIL
    ['domain' => 'http://twentytwentyone.com', 'good' => true],
    ['domain' => 'http://twinset.com', 'good' => true],
    ['domain' => 'http://typehype.com', 'good' => true],
    ['domain' => 'http://uashmama.nl', 'good' => true],
    ['domain' => 'http://ullapopken.be', 'good' => true],
    ['domain' => 'http://ullapopken.nl', 'good' => true],
    ['domain' => 'http://uniqfind.com', 'good' => true],
    ['domain' => 'http://unitedbrands.be', 'good' => true],
    ['domain' => 'http://unitednude.com', 'good' => true],
    ['domain' => 'http://urban-outfitters.co.uk', 'good' => true], // FAIL
    ['domain' => 'http://urbanhippies.nl', 'good' => true], // FAIL
    ['domain' => 'http://urbanminishop.com', 'good' => true], // FAIL
    ['domain' => 'http://urbanoutfitters.com', 'good' => true], // FAIL
    ['domain' => 'http://usfoodz.nl', 'good' => true], // FAIL
    ['domain' => 'http://uwantisell.nl', 'good' => true],
    ['domain' => 'http://uwkringding.be', 'good' => true],
    ['domain' => 'http://va-tout.be', 'good' => true],
    ['domain' => 'http://vakantieveilingen.be', 'good' => true],
    ['domain' => 'http://valerieberckmans.be', 'good' => null], // ?
    ['domain' => 'http://vandalenschoenen.be', 'good' => true],
    ['domain' => 'http://vandenborre.be', 'good' => true],
    ['domain' => 'http://vanharen.nl', 'good' => true],
    ['domain' => 'http://vanikke.nl', 'good' => true],
    ['domain' => 'http://vanilia.com', 'good' => true],
    ['domain' => 'http://vanmarieke.nl', 'good' => true],
    ['domain' => 'http://vans.eu', 'good' => true],
    ['domain' => 'http://vdbfashion.be', 'good' => true],
    ['domain' => 'http://veloretti.com', 'good' => true],
    ['domain' => 'http://vente-exclusive.com', 'good' => true],
    ['domain' => 'http://veritas.be', 'good' => true],
    ['domain' => 'http://vermiljoenshop.be', 'good' => true],
    ['domain' => 'http://veromoda.com', 'good' => true], // FAIL
    ['domain' => 'http://veroniquescloset.be', 'good' => true], // FAIL
    ['domain' => 'http://veroniquesneyaert.be', 'good' => true],
    ['domain' => 'http://verycherry.nl', 'good' => true],
    ['domain' => 'http://victoriassecret.com', 'good' => true],
    ['domain' => 'http://vida-design.be', 'good' => true],
    ['domain' => 'http://villameliefste.nl', 'good' => true],
    ['domain' => 'http://vipp.com', 'good' => true],
    ['domain' => 'http://vivemamaison.be', 'good' => true],
    ['domain' => 'http://vivrebrocante.nl', 'good' => true],
    ['domain' => 'http://vlijtigliesje.be', 'good' => true],
    ['domain' => 'http://vtwonen.be', 'good' => true],
    ['domain' => 'http://vtwonen.nl', 'good' => true],
    ['domain' => 'http://waaaw.nl', 'good' => true],
    ['domain' => 'http://wanderandco.com', 'good' => true],
    ['domain' => 'http://wannafeelgood.nl', 'good' => true],
    ['domain' => 'http://wannekes.com', 'good' => true],
    ['domain' => 'http://wassenop30graden.be', 'good' => true],
    ['domain' => 'http://webshop.stoffenvanleuven.be', 'good' => false], // X
    ['domain' => 'http://webstash.nl', 'good' => true],
    ['domain' => 'http://weddingdeco.nl', 'good' => true],
    ['domain' => 'http://weekend.knack.be', 'good' => true],
    ['domain' => 'http://weetaps.com', 'good' => true],
    ['domain' => 'http://wehkamp.com', 'good' => true],
    ['domain' => 'http://welcometobutik.com', 'good' => true], // FAIL
    ['domain' => 'http://welikefashion.com', 'good' => true],
    ['domain' => 'http://welovefrugi.com', 'good' => true],
    ['domain' => 'http://welovelonglegs.nl', 'good' => true],
    ['domain' => 'http://welovemusthaves.com', 'good' => true],
    ['domain' => 'http://welovestijl.com', 'good' => true],
    ['domain' => 'http://wenn-sieraden.nl', 'good' => true],
    ['domain' => 'http://west-end.be', 'good' => true],
    ['domain' => 'http://westwing.nl', 'good' => true],
    ['domain' => 'http://wewillsockyou.com', 'good' => true],
    ['domain' => 'http://whistles.com', 'good' => true],
    ['domain' => 'http://wildfox.com', 'good' => true],
    ['domain' => 'http://wildvanstof.be', 'good' => true],
    ['domain' => 'http://wilsonandfrenchy.com.au', 'good' => true],
    ['domain' => 'http://wimmeeussen.be', 'good' => true],
    ['domain' => 'http://winkelvanpauline.nl', 'good' => true],
    ['domain' => 'http://winkln.be', 'good' => true], // FAIL
    ['domain' => 'http://wintercroft.com', 'good' => true],
    ['domain' => 'http://winwinner.be', 'good' => true],
    ['domain' => 'http://wish-fashion.com', 'good' => true],
    ['domain' => 'http://wolfenwolkje.be', 'good' => true],
    ['domain' => 'http://wondermade.com.au', 'good' => true],
    ['domain' => 'http://wonenmetlef.nl', 'good' => true],
    ['domain' => 'http://woodwoven.com', 'good' => true],
    ['domain' => 'http://wooop.fr', 'good' => true],
    ['domain' => 'http://wouters-hendrix.com', 'good' => true],
    ['domain' => 'http://www.fr.maje.com', 'good' => true], // FAIL
    ['domain' => 'http://www.laredoude', 'good' => true], // FAIL
    ['domain' => 'http://www.orangebag.nlwww.orangebag.nl', 'good' => true],
    ['domain' => 'http://www2.hm.com', 'good' => true],
    ['domain' => 'http://wwww.debijenkorf.be', 'good' => true], // FAIL
    ['domain' => 'http://xandi.nl', 'good' => true],
    ['domain' => 'http://xpclothing.nl', 'good' => true],
    ['domain' => 'http://xplosion.be', 'good' => true],
    ['domain' => 'http://xtasa.be', 'good' => true],
    ['domain' => 'http://ydee.be', 'good' => true],
    ['domain' => 'http://yfyjewels.nl', 'good' => true],
    ['domain' => 'http://yoox.com', 'good' => true],
    ['domain' => 'http://youngoneapparel.com', 'good' => true], // FAIL
    ['domain' => 'http://yournextjewel.com', 'good' => true],
    ['domain' => 'http://yoursurprise.be', 'good' => true],
    ['domain' => 'http://yves-rocher.be', 'good' => true],
    ['domain' => 'http://zadig-et-voltaire.com', 'good' => true],
    ['domain' => 'http://zahia.be', 'good' => true],
    ['domain' => 'http://zalando-lounge.be', 'good' => true],
    ['domain' => 'http://zalando.be', 'good' => true],
    ['domain' => 'http://zalando.com', 'good' => true],
    ['domain' => 'http://zangra.com', 'good' => true],
    ['domain' => 'http://zara.be', 'good' => true],
    ['domain' => 'http://zara.com', 'good' => true],
    ['domain' => 'http://zata.be', 'good' => true], // FAIL
    ['domain' => 'http://zeb.be', 'good' => true],
    ['domain' => 'http://zebrazonderstrepen.com', 'good' => true],
    ['domain' => 'http://zilverblauw.nl', 'good' => true],
    ['domain' => 'http://zinkenzo.nl', 'good' => true],
    ['domain' => 'http://zlando.be', 'good' => true],
    ['domain' => 'http://zoekarssen.com', 'good' => true],
    ['domain' => 'http://zoeva-shop.de', 'good' => null], // ?
    ['domain' => 'http://zomerzoen.be', 'good' => false], // X
    ['domain' => 'http://zonnehoed.be', 'good' => false], // X
    ['domain' => 'http://zorabyl.com', 'good' => true],
    ['domain' => 'http://zoyou.nl', 'good' => true],
    ['domain' => 'http://zsazsashop.com', 'good' => null], // ?
    ['domain' => 'http://zuidshop.be', 'good' => true], // FAIL
    ['domain' => 'http://zuiver.be', 'good' => true], // FAIL
    ['domain' => 'http://zusenzolifestyle.nl', 'good' => true],
    ['domain' => 'http://zweuds.be', 'good' => true],
];
set_time_limit(0);
$f = fopen('test_full.html', 'w');
fwrite($f, "<!DOCTYPE html><html><head><title></title><style>td {padding:5px;}</style></head><body><table>");
foreach ($domains as $domain) {
    echo $domain['domain'] . " - " . $domain['good'] . "\n";
    fwrite($f, "<tr>");
    $error = '';
    $result = null;
    try {
        $visit = $hyena->visit($domain['domain']);
        if ($visit != null) {
            $result = $visit->extract(['name', 'images'], [
                'min_image_height' => 300,
                'min_image_width'  => 300,
            ]);
            $color = is_null($domain['good']) ? '#f2e785' : ($domain['good'] === true ? '#4caf50' : '#f44336');
        } else {
            $error = 'Can\'t get domain data';
            $color = '#9e9e9e';
        }
    } catch (Exception $e) {
        $color = '#9e9e9e';
        $error = $e->getMessage();
    }
    echo $error . "\n";
    fwrite($f, sprintf("<td style='background: %1\$s'><a href='%2\$s' target='_blank'>%2\$s</a></td>", $color, $domain['domain']));
    fwrite($f, sprintf("<td style='background: %s'>%s</td>", $color, $result ? $result['name'] : ''));
    fwrite($f, sprintf("<td style='background: %s'>%s</td>", $color, $result ? implode('<br>', array_map(function ($link) {
        return sprintf('<a href=\'%1$s\' target=\'_blank\'>%1$s</a>', $link);
    }, $result['images'])) : ''));
    fwrite($f, sprintf("<td style='background: %s'>%s</td>", $color, htmlentities($error)));
    fwrite($f, "</tr>");
}
fwrite($f, "</table></body></html>");
fclose($f);
